
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Sesame Ariselu (Special)',
    category: 'Sweets',
    price: 450,
    originalPrice: 599,
    image: 'https://ramadevifoods.com/cdn/shop/files/Sesame-Ariselu.png?v=1718777172&width=900',
    rating: 4.8,
    reviews: 124,
    description: 'Authentic traditional sweet made with rice flour and pure jaggery, topped with white sesame seeds.',
    ingredients: ['Rice Flour', 'Organic Jaggery', 'Pure Ghee', 'Sesame Seeds', 'Cardamom'],
    shelfLife: '30 Days',
    storage: 'Store in an airtight container at room temperature.',
    isBestSeller: true,
    onOffer: true,
    bestFor: 'Festive occasions',
    prepMethod: 'Naturally fermented dough, hand-shaped and deep fried in pure ghee.',
    usageTips: ['Pairs best with a warm cup of milk', 'Warm slightly before serving for a melt-in-mouth texture']
  },
  {
    id: 's1',
    name: 'Ribbon Murukku',
    category: 'Snacks',
    price: 180,
    image: 'https://ramadevifoods.com/cdn/shop/files/Murukku_4675e19c-e110-4bcc-9b20-02c1cda92508.jpg?v=1717133853&width=900',
    rating: 4.9,
    reviews: 88,
    description: 'Crispy, ribbon-shaped savory snack made with gram flour and rice flour, flavored with ajwain.',
    ingredients: ['Rice Flour', 'Gram Flour', 'Butter', 'Ajwain', 'Red Chilli Powder', 'Salt'],
    shelfLife: '60 Days',
    storage: 'Keep in an airtight container.',
    isBestSeller: true,
    bestFor: 'Daily use',
    usageTips: ['Perfect tea-time companion', 'Serve with hot coffee']
  },
  {
    id: 's2',
    name: 'Pappu Chekkalu',
    category: 'Snacks',
    price: 210,
    image: 'https://ramadevifoods.com/cdn/shop/files/Chekkalu.jpg?v=1717133930&width=800',
    rating: 4.8,
    reviews: 65,
    description: 'Traditional flat rice crackers loaded with chana dal, curry leaves, and ginger-green chilli paste.',
    ingredients: ['Rice Flour', 'Chana Dal', 'Curry Leaves', 'Ginger', 'Green Chilli', 'Oil'],
    shelfLife: '45 Days',
    storage: 'Store in a dry, cool place.',
    bestFor: 'Festive occasions',
    usageTips: ['Pairs perfectly with curd rice', 'A must-have for Janmashtami']
  },
  {
    id: '40',
    name: 'Black Sesame Chikki',
    category: 'Sweets',
    price: 260,
    image: 'https://ramadevifoods.com/cdn/shop/files/Nuvvulachikki.png?v=1718778613&width=800',
    rating: 4.9,
    reviews: 82,
    description: 'Nutrient-rich bars made with premium black sesame seeds and natural jaggery. A healthy snack full of iron.',
    ingredients: ['Black Sesame Seeds', 'Jaggery', 'Ghee', 'Cardamom'],
    shelfLife: '90 Days',
    storage: 'Store in a cool, dry place.',
    bestFor: 'Daily use',
    usageTips: ['Excellent post-workout snack', 'Great for natural iron boost']
  },
  {
    id: '41',
    name: 'Pulihora Paste',
    category: 'Pickles',
    price: 280,
    image: 'https://ramadevifoods.com/cdn/shop/files/PulihoraPaste.jpg?v=1717142117&width=800',
    rating: 4.9,
    reviews: 145,
    description: 'Traditional Andhra-style Tamarind Rice Paste. The perfect base for authentic festive rice.',
    ingredients: ['Tamarind Pulp', 'Sesame Oil', 'Red Chillies', 'Curry Leaves', 'Turmeric', 'Fenugreek'],
    shelfLife: '6 Months',
    storage: 'Keep in an airtight jar. Use a dry spoon.',
    bestFor: 'Festive occasions',
    isBestSeller: true,
    usageTips: ['Mix with hot rice and peanuts', 'Great for travel meals']
  },
  {
    id: '42',
    name: 'Tomato Pickle',
    category: 'Pickles',
    price: 240,
    image: 'https://ramadevifoods.com/cdn/shop/files/TomatoPickle2.jpg?v=1717141712&width=800',
    rating: 4.7,
    reviews: 110,
    description: 'Zesty sun-dried tomato pickle prepared with traditional home-ground spices.',
    ingredients: ['Tomatoes', 'Red Chilli Powder', 'Sesame Oil', 'Fenugreek', 'Garlic'],
    shelfLife: '6 Months',
    storage: 'Refrigerate for long-lasting freshness.',
    bestFor: 'Daily use',
    usageTips: ['Best with hot rice and ghee', 'Adds zest to plain curd rice']
  },
  {
    id: '43',
    name: 'Red Chilli Pickle',
    category: 'Pickles',
    price: 310,
    image: 'https://ramadevifoods.com/cdn/shop/files/Redchillipickle2.jpg?v=1717141930&width=800',
    rating: 4.8,
    reviews: 95,
    description: 'Fiery and bold red chilli pickle made with hand-picked whole sun-ripened chillies.',
    ingredients: ['Whole Red Chillies', 'Mustard Powder', 'Salt', 'Sesame Oil', 'Aged Tamarind'],
    shelfLife: '8 Months',
    storage: 'Keep top layer covered with oil.',
    bestFor: 'Daily use',
    isBestSeller: true,
    usageTips: ['Perfect side for Upma and Pesarattu', 'Great for spice enthusiasts']
  },
  {
    id: '44',
    name: 'Tamarind Pickle',
    category: 'Pickles',
    price: 290,
    image: 'https://ramadevifoods.com/cdn/shop/files/TamarindPickle.jpg?v=1742207876&width=800',
    rating: 4.8,
    reviews: 78,
    description: 'Tangy and spiced tamarind pulp pickle, a staple in traditional South Indian homes.',
    ingredients: ['Aged Tamarind', 'Rock Salt', 'Red Chilli Powder', 'Fenugreek', 'Oil'],
    shelfLife: '12 Months',
    storage: 'Store in a dry ceramic jar.',
    bestFor: 'Daily use',
    usageTips: ['Perfect accompaniment for curd rice', 'Base for tangy gravies']
  },
  {
    id: '45',
    name: 'Podi Chutney',
    category: 'Spicy Powders',
    price: 180,
    image: 'https://ramadevifoods.com/cdn/shop/files/Podichutney.jpg?v=1717410170&width=800',
    rating: 4.9,
    reviews: 132,
    description: 'A versatile dry chutney powder made from roasted lentils and aromatic spices.',
    ingredients: ['Lentils', 'Red Chillies', 'Hing', 'Curry Leaves', 'Garlic'],
    shelfLife: '4 Months',
    storage: 'Airtight container required.',
    bestFor: 'Daily use',
    usageTips: ['Mix with oil for Idli/Dosa dipping', 'Sprinkle over ghee roast']
  },
  {
    id: '46',
    name: 'Groundnut Spicy Powder',
    category: 'Spicy Powders',
    price: 210,
    image: 'https://ramadevifoods.com/cdn/shop/files/GroundnutspicyPowder.jpg?v=1717409804&width=800',
    rating: 5.0,
    reviews: 156,
    description: 'Rich, nutty, and spicy peanut powder (Chenikaya Podi) - a protein-rich delight.',
    ingredients: ['Roasted Peanuts', 'Red Chilli', 'Garlic', 'Cumin'],
    shelfLife: '3 Months',
    storage: 'Keep in a dry place.',
    bestFor: 'Daily use',
    isBestSeller: true,
    usageTips: ['Best with hot rice and ghee', 'Perfect with Idli/Dosa']
  },
  {
    id: '47',
    name: 'Idli & Dosa Powder',
    category: 'Spicy Powders',
    price: 160,
    image: 'https://ramadevifoods.com/cdn/shop/files/Idli_DosaPowder2.jpg?v=1717409536&width=800',
    rating: 4.9,
    reviews: 210,
    description: 'Traditional "Gunpowder" Milagai Podi. Coarse, spicy, and perfectly roasted.',
    ingredients: ['Urad Dal', 'Chana Dal', 'Red Chillies', 'Sesame Seeds', 'Curry Leaves'],
    shelfLife: '6 Months',
    storage: 'Store in an airtight jar.',
    bestFor: 'Daily use',
    usageTips: ['Classic Idli companion', 'Great with Sesame oil']
  },
  {
    id: '48',
    name: 'Curry Leaves Powder',
    category: 'Spicy Powders',
    price: 200,
    image: 'https://ramadevifoods.com/cdn/shop/files/Curryleavespowder2.jpg?v=1717409413&width=800',
    rating: 4.8,
    reviews: 94,
    description: 'Highly nutritious and aromatic powder made from sun-dried organic curry leaves.',
    ingredients: ['Fresh Curry Leaves', 'Black Gram', 'Lentils', 'Garlic', 'Tamarind'],
    shelfLife: '4 Months',
    storage: 'Keep away from moisture.',
    bestFor: 'Daily use',
    usageTips: ['Heart-healthy addition to rice', 'Excellent for digestion']
  },
  {
    id: '49',
    name: 'Podi Lovers Box',
    category: 'Combos',
    price: 1899,
    originalPrice: 2200,
    image: 'https://ramadevifoods.com/cdn/shop/files/Podi_Lovers_Box_1.jpg?v=1721798120&width=800',
    rating: 5.0,
    reviews: 45,
    description: 'The ultimate gift for spice lovers. 16 Types of authentic Podis (100g each) in a premium box.',
    ingredients: ['Assorted Traditional Spicy Powders'],
    shelfLife: '4 Months',
    storage: 'Store individual packs in jars.',
    onOffer: true,
    bestFor: 'Gifting',
    usageTips: ['Perfect housewarming gift', 'Flavor variety for every meal']
  },
  {
    id: '50',
    name: 'Flaxseed Laddu',
    category: 'Sweets',
    price: 490,
    image: 'https://ramadevifoods.com/cdn/shop/files/Avisaginjala.png?v=1724147668&width=800',
    rating: 4.9,
    reviews: 62,
    description: 'Power-packed healthy laddus (Avisaginjala) rich in Omega-3 and fiber.',
    ingredients: ['Roasted Flaxseeds', 'Organic Jaggery', 'Pure Ghee', 'Dry Ginger'],
    shelfLife: '30 Days',
    storage: 'Store in an airtight container.',
    bestFor: 'Daily use',
    usageTips: ['Great for morning energy', 'Guilt-free dessert']
  },
  {
    id: '2',
    name: 'Bellam Gavvalu',
    category: 'Sweets',
    price: 380,
    image: 'https://ramadevifoods.com/cdn/shop/files/Jaggery-Gavvalu.png?v=1718777310&width=1000',
    rating: 4.57,
    reviews: 215,
    description: 'Traditional jaggery-dipped shells. Crunchy on the outside and sweet on the inside.',
    ingredients: ['All Purpose Flour', 'Jaggery', 'Pure Ghee', 'Cardamom'],
    shelfLife: '45 Days',
    storage: 'Keep in a dry, cool place in an airtight jar.',
    bestFor: 'Daily use',
    prepMethod: 'Hand-pressed shells deep fried and coated in rich jaggery syrup.',
    usageTips: ['Great evening snack with tea', 'Kids love these crunchy treats']
  },
  {
    id: '3',
    name: 'Sunnundalu (Urad Dal Laddu)',
    category: 'Sweets',
    price: 420,
    image: 'https://ramadevifoods.com/cdn/shop/files/Sunnundalu.png?v=1718778162&width=800',
    rating: 4.9,
    reviews: 312,
    description: 'Nutritious and delicious Urad Dal Ladoo made with pure ghee and organic jaggery.',
    ingredients: ['Urad Dal', 'Organic Jaggery', 'Pure Cow Ghee'],
    shelfLife: '20 Days',
    storage: 'Refrigeration not required. Keep in airtight container.',
    isBestSeller: true,
    bestFor: 'Gifting',
    prepMethod: 'Slow-roasted Urad Dal ground to perfection and mixed with warm ghee and jaggery.',
    usageTips: ['Highly nutritious for growing children', 'Excellent energy booster']
  },
  {
    id: '17',
    name: 'Kajjikayalu / Karjikai / Gujiya',
    category: 'Sweets',
    price: 480,
    image: 'https://ramadevifoods.com/cdn/shop/files/1_90d79a72-9e01-47d7-a82b-595355f71315.jpg?v=1762096370&width=900',
    rating: 4.7,
    reviews: 142,
    description: 'Traditional crescent-shaped dumplings filled with a sweet mixture of coconut and semolina.',
    ingredients: ['Maida', 'Semolina', 'Grated Coconut', 'Sugar', 'Ghee'],
    shelfLife: '20 Days',
    storage: 'Store in a cool, dry place.',
    bestFor: 'Festive occasions',
    usageTips: ['Excellent for Diwali and Holi festivals', 'Serve with a drizzle of warm ghee']
  },
  {
    id: '18',
    name: 'Boondi Laddu',
    category: 'Sweets',
    price: 390,
    image: 'https://ramadevifoods.com/cdn/shop/files/laddu-image.png?v=1730184785&width=900',
    rating: 4.9,
    reviews: 267,
    description: 'Classic Indian sweet made from tiny fried gram flour balls soaked in flavored sugar syrup.',
    ingredients: ['Gram Flour', 'Sugar', 'Ghee', 'Cardamom', 'Melon Seeds'],
    shelfLife: '15 Days',
    storage: 'Store in an airtight container.',
    isBestSeller: true,
    bestFor: 'Gifting',
    usageTips: ['The quintessential celebration sweet', 'Pairs well with savory snacks']
  }
];

export const CATEGORIES = [
  { 
    name: 'Sweets', 
    image: 'https://ramadevifoods.com/cdn/shop/files/Sesame-Ariselu.png?v=1718777172&width=900',
    filter: 'Sweets'
  },
  { 
    name: 'Pickles', 
    image: 'https://ramadevifoods.com/cdn/shop/files/pickle-love.jpg?v=1721797884&width=900',
    filter: 'Pickles'
  },
  { 
    name: 'Spicy Powders', 
    image: 'https://ramadevifoods.com/cdn/shop/files/Coconut_garlicspicypowder2.jpg?v=1717409589&width=800',
    filter: 'Spicy Powders'
  },
  { 
    name: 'Snacks', 
    image: 'https://ramadevifoods.com/cdn/shop/files/Murukku_4675e19c-e110-4bcc-9b20-02c1cda92508.jpg?v=1717133853&width=900',
    filter: 'Snacks'
  },
  { 
    name: 'Combos', 
    image: 'https://ramadevifoods.com/cdn/shop/files/Podi_Lovers_Box_1.jpg?v=1721798120&width=800',
    filter: 'Combos'
  }
];
